# Generated by Django 5.2.4 on 2026-05-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_deal_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE')], default='PENDING', max_length=20),
        ),
    ]
