# Generated by Django 5.2.4 on 2026-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lead_source',
            field=models.CharField(choices=[('DIRECT', 'Direct Search'), ('PAID', 'Paid Campaigns'), ('REFERRAL', 'Referrals'), ('SOCIAL', 'Social Media')], default='DIRECT', max_length=20),
        ),
    ]
