# Generated by Django 6.0.2 on 2026-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_calendarevent_id_alter_deal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
