# Generated by Django 6.0.2 on 2026-05-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_calendarevent_all_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
