# Generated by Copilot on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_calendarevent_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
