# Generated by Django 6.0.2 on 2026-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_calendarevent_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#0e4d46', max_length=20),
        ),
    ]
