# Generated by Django 6.0.2 on 2026-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_calendarevent_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('reminder', 'Reminder'), ('personal', 'Personalized'), ('other', 'Other')], max_length=20),
        ),
    ]
