# Generated by Django 6.0.2 on 2026-06-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_calendarevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_view',
            field=models.CharField(default='list', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='in_app_notif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='English (United States)', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor',
            field=models.BooleanField(default=True),
        ),
    ]
