# Generated by Django 5.2.4 on 2026-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
