# Generated by Django 5.2.4 on 2026-05-07 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_target_target_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['-month']},
        ),
        migrations.AlterField(
            model_name='target',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('user', 'month')},
        ),
    ]
